// @vitest-environment jsdom
import * as React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import fixtures from "@/components/modernization/__tests__/fixtures.json";

/**
 * Phase F — the Migration Strategy page (research §6.4), rendering what the BACKEND produces for two
 * unrelated systems (`fixtures.json` → `migration_plan` = ClaimTrack, `migration_plan_payroll` =
 * Payroll; regenerated by help/Track-3/tools/regen_view_fixtures.py, never hand-edited).
 *
 *   - the page: the access gate, no legacy-code controls (this agent works from documents), the
 *     stub is gone;
 *   - sign-off: the producer is told why not; the hand-over names Equivalence Testing;
 *   - the ledger panel says what approval does, before and after, in every version state;
 *   - the view: timeline with the brief's dates, waves with entry/exit/rollback, criteria with their
 *     normalization, baselines with late ones flagged, every computed calendar conflict with whether
 *     it was reported and resolved, the order it started from (a cycle shown), effort as an estimate.
 */

const PROJECT = "33333333-3333-3333-3333-333333333333";

const state = vi.hoisted(() => ({
  track: "modernization" as string,
  me: { id: "u-arch2", email: "arch2@example.com" },
  version: {} as Record<string, unknown>,
  ledger: [] as { moduleId: string; moduleName: string; legacyPath: string; state: string; wave?: string | null }[],
  legacyCalls: 0,
  documentStages: [] as string[],
}));

vi.mock("next/navigation", () => ({
  useParams: () => ({ id: PROJECT }),
  useRouter: () => ({ push: vi.fn(), replace: vi.fn() }),
  useSearchParams: () => new URLSearchParams(),
  usePathname: () => "/",
}));
vi.mock("@/hooks/use-session", () => ({
  useSession: () => ({ user: state.me, permissions: ["artifact:view", "run:create", "artifact:approve_strategy"] }),
}));
vi.mock("@/hooks/use-agent-chat", () => ({
  useAgentChat: () => ({
    busy: false, messages: [], sessions: [], sessionId: null, attachments: [], documents: [],
    send: vi.fn(), cancel: vi.fn(), newChat: vi.fn(), selectSession: vi.fn(),
    attachFiles: vi.fn(), removeAttachment: vi.fn(),
  }),
}));
vi.mock("@/hooks/use-chat-deep-link", () => ({ useChatDeepLink: () => null }));
vi.mock("@/lib/api/projects", () => ({
  getProject: async () => ({ id: PROJECT, name: "ClaimTrack", track: state.track }),
}));
vi.mock("@/lib/api/modernization", async (orig) => ({
  ...(await (orig() as Promise<Record<string, unknown>>)),
  getVersionPacket: async (_p: string, stage: string, version: number) => ({ stage, version, ok: true, problems: [], packet: {} }),
  getLegacyCode: async () => {
    state.legacyCalls++;
    return { projectId: PROJECT, status: "none", request: null, error: "", pull: null };
  },
}));
vi.mock("@/lib/api/modernization-programme", async (orig) => ({
  ...(await (orig() as Promise<Record<string, unknown>>)),
  getLedger: async () => ({ projectId: PROJECT, states: [], modules: state.ledger }),
}));
vi.mock("@/lib/api/artifact-versions", async (orig) => ({
  ...(await (orig() as Promise<Record<string, unknown>>)),
  listStageVersions: async () => [state.version],
  getStageVersion: async () => state.version,
  getVersionConsumers: async () => ({ stage: "strategy", version: 1, status: "published", contentHash: "h", consumers: [] }),
  getVersionStaleness: async () => ({ stage: "strategy", version: 1, pinned: true, stale: false, inputs: [] }),
  publishStageVersion: vi.fn(),
  rejectStageVersion: vi.fn(),
}));
vi.mock("@/components/app/document-list", () => ({
  DocumentList: ({ stage }: { stage: string }) => {
    state.documentStages.push(stage);
    return <section aria-label="documents">documents for {stage}</section>;
  },
}));
vi.mock("@/components/app/tech-stack-chip", () => ({ TechStackChip: () => <span>tech stack chip</span> }));
vi.mock("@/components/app/model-selector", () => ({ ModelSelector: () => null }));
vi.mock("@/components/app/agent-chat-drawer", () => ({ AgentChatDrawer: () => null }));

import StrategyPage from "@/app/(app)/projects/[id]/strategy/page";
import { StrategyView, strategyLedgerText, timelineMarkers } from "@/components/modernization/strategy-view";
import { VersionView } from "@/components/modernization/version-view";
import { MigrationPlan } from "@/lib/schemas/modernization";

const CLAIMTRACK = MigrationPlan.parse(fixtures.migration_plan);
const PAYROLL = MigrationPlan.parse(fixtures.migration_plan_payroll);

function wrap(ui: React.ReactElement) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(<QueryClientProvider client={client}>{ui}</QueryClientProvider>);
}

beforeEach(() => {
  state.track = "modernization";
  state.me = { id: "u-arch2", email: "arch2@example.com" };
  state.version = { id: "v1", stage: "strategy", version: 1, status: "draft", contentHash: "h",
    producedBy: "arch@example.com", covers: [], payload: fixtures.migration_plan };
  state.ledger = [];
  state.legacyCalls = 0;
  state.documentStages = [];
});
afterEach(cleanup);

describe("the page", () => {
  it("explains instead of opening a chat on a project of another track", async () => {
    state.track = "greenfield";
    wrap(<StrategyPage />);
    expect(await screen.findByText("Migration Strategy is a Code Modernization agent")).toBeTruthy();
  });

  it("works from documents: no legacy-code status, pull button or query", async () => {
    wrap(<StrategyPage />);
    expect(await screen.findByText("documents for strategy")).toBeTruthy();
    expect(screen.getByRole("heading", { name: "How a migration plan gets made" })).toBeTruthy();
    expect(screen.queryByRole("button", { name: /Pull legacy code|Pull again/ })).toBeNull();
    expect(state.legacyCalls).toBe(0);
    expect(screen.queryByText(/No migration plan yet/)).toBeNull(); // the stub is gone
  });
});

function versionView() {
  return wrap(
    <VersionView projectId={PROJECT as never} stage="strategy" noun="migration plan" version={1}
      render={(payload, detail) => (
        <StrategyView plan={MigrationPlan.parse(payload)} projectId={PROJECT as never}
          approved={detail.status === "published"} status={detail.status} />
      )} />,
  );
}

describe("sign-off, hand-over and the ledger", () => {
  it("offers Approve to another Architect and hands over to Equivalence Testing", async () => {
    versionView();
    expect(await screen.findByRole("button", { name: "Approve" })).toBeTruthy();
    expect(await screen.findByText("Ready to hand to Equivalence Testing once approved.")).toBeTruthy();
    const panel = screen.getByRole("region", { name: "Module ledger" });
    expect(panel.textContent).toContain("Approving this version sequences these 5 modules");
  });

  it("tells the producer why they cannot decide it", async () => {
    state.me = { id: "u-arch", email: "arch@example.com" };
    versionView();
    expect(await screen.findByText(/You produced this migration plan, so you can.t approve it/)).toBeTruthy();
  });

  it("shows each module's state and flags one sequenced into another wave", async () => {
    state.version = { ...state.version, status: "published" };
    state.ledger = [{ moduleId: "M-05", moduleName: "claimtrack-reports", legacyPath: "claimtrack-reports", state: "sequenced", wave: "W1" },
      { moduleId: "M-03", moduleName: "claimtrack-batch", legacyPath: "claimtrack-batch", state: "baselined", wave: "W9" }];
    versionView();
    const panel = await screen.findByRole("region", { name: "Module ledger" });
    await waitFor(() => expect(within(panel).getByText("Baselined in W9")).toBeTruthy());
    expect(within(panel).getByText("Sequenced")).toBeTruthy();
    expect(within(panel).getAllByText("not on the ledger — design not approved")).toHaveLength(3);
  });

  it("re-reads the ledger when the version is approved, so the panel shows the new states", async () => {
    const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
    const view = (approved: boolean) => (
      <QueryClientProvider client={client}>
        <StrategyView plan={CLAIMTRACK} projectId={PROJECT as never} approved={approved}
          status={approved ? "published" : "draft"} />
      </QueryClientProvider>
    );
    const { rerender } = render(view(false));
    const panel = await screen.findByRole("region", { name: "Module ledger" });
    await waitFor(() => expect(within(panel).getAllByText("not on the ledger — design not approved")).toHaveLength(5));
    state.ledger = [{ moduleId: "M-05", moduleName: "claimtrack-reports", legacyPath: "claimtrack-reports", state: "sequenced", wave: "W1" }];
    rerender(view(true));
    await waitFor(() => expect(within(panel).getByText("Sequenced")).toBeTruthy());
  });

  it("says only what is true in every version state", () => {
    expect(strategyLedgerText(false, "rejected", 5)).toBe(
      "This version was rejected, so it cannot be approved and does not change the ledger.");
    expect(strategyLedgerText(false, "superseded", 5)).toContain("A newer plan has been approved since");
    expect(strategyLedgerText(true, "published", 5)).toContain("sequenced on the migration ledger");
  });
});

describe("the plan view — ClaimTrack", () => {
  it("summarises the plan and puts the brief's dates on the timeline", () => {
    wrap(<StrategyView plan={CLAIMTRACK} />);
    const summary = screen.getByRole("region", { name: "Migration plan summary" });
    expect(summary.textContent).toContain("W0 + 4");
    expect(summary.textContent).toContain("Brief v1 (approved)");
    const timeline = screen.getByRole("region", { name: "Timeline" });
    expect(within(timeline).getByTitle(/^W3 Settlement batch: /)).toBeTruthy();
    const dates = within(timeline).getByRole("list", { name: "Dates on the timeline" });
    expect(dates.textContent).toMatch(/Deadline .*2027/);
    expect(dates.textContent).toMatch(/Legacy freeze .*2027/);
  });

  it("shows each wave's entry, exit, rollback and parallel run", () => {
    wrap(<StrategyView plan={CLAIMTRACK} />);
    const w3 = screen.getByRole("listitem", { name: "W3 Settlement batch" });
    expect(w3.textContent).toContain("EC-02; EC-09; EC-10; EC-08");
    expect(w3.textContent).toContain("4 weeks — legacy stays the system of record");
    expect(w3.textContent).toContain("When any settlement difference after the send switch: switch sending back to legacy");
    expect(w3.textContent).toContain("In-place upgrade + Parallel run");
  });

  it("lists criteria with their normalization, filterable by module", async () => {
    const user = userEvent.setup();
    wrap(<StrategyView plan={CLAIMTRACK} />);
    await user.click(screen.getByRole("tab", { name: /Criteria/ }));
    const ec02 = screen.getByRole("listitem", { name: "EC-02" });
    expect(within(ec02).getByRole("list", { name: "EC-02 normalization" }).textContent).toContain("HDR-07 creation time");
    expect(ec02.textContent).toContain("Byte-identical");
    expect(screen.getByRole("listitem", { name: "EC-01" }).textContent).toContain("No normalization: every field must match.");
    await user.click(screen.getByRole("button", { name: "M-03" }));
    const cards = screen.getAllByRole("listitem").map((li) => li.getAttribute("aria-label")).filter((l) => l?.startsWith("EC-"));
    expect(cards).toEqual(["EC-02", "EC-09", "EC-10"]);
  });

  it("flags a baseline the calendar check found late", async () => {
    const user = userEvent.setup();
    wrap(<StrategyView plan={CLAIMTRACK} />);
    await user.click(screen.getByRole("tab", { name: /Baselines/ }));
    const row = screen.getByText("EC-03").closest("tr")!;
    expect(within(row).getByText("conflict")).toBeTruthy();
    expect(within(screen.getByText("EC-01").closest("tr")!).queryByText("conflict")).toBeNull();
  });

  it("shows every computed conflict, and whether it was reported and resolved", async () => {
    const user = userEvent.setup();
    const unresolved = { ...CLAIMTRACK, calendar_conflicts: CLAIMTRACK.calendar_conflicts.map((c) =>
      c.ref === "baseline-late:EC-03" ? { ...c, resolution: null } : c) };
    wrap(<StrategyView plan={unresolved} />);
    await user.click(screen.getByRole("tab", { name: /Calendar/ }));
    const c = screen.getByRole("listitem", { name: "baseline-late:EC-03" });
    expect(within(c).getByText("reported — open")).toBeTruthy();
    expect(screen.getAllByText("raised in the conversation")).toHaveLength(2);
  });

  it("says effort is an estimate and shows sizes that were not measured", async () => {
    const user = userEvent.setup();
    wrap(<StrategyView plan={CLAIMTRACK} />);
    await user.click(screen.getByRole("tab", { name: /Effort/ }));
    expect(screen.getByText(/An ESTIMATE, not a quote/)).toBeTruthy();
    expect(screen.getByText(/Total from the table: not estimated/)).toBeTruthy();
  });
});

describe("the plan view — Payroll (a different system entirely)", () => {
  it("shows the cycle, the kept module and the order exceptions", async () => {
    const user = userEvent.setup();
    wrap(<StrategyView plan={PAYROLL} />);
    expect(screen.getByRole("listitem", { name: "Order exceptions" }).textContent).toContain("M-04 before M-01");
    await user.click(screen.getByRole("tab", { name: /Order/ }));
    expect(screen.getByText("cycle")).toBeTruthy();
    expect(screen.getByText(/Kept as they are \(move in no wave\): M-05/)).toBeTruthy();
  });

  it("puts the change freeze and the licence renewal on the timeline, and needs no deadline", () => {
    const labels = timelineMarkers(PAYROLL).map((m) => m.label);
    expect(labels.some((l) => l.startsWith("Legacy freeze"))).toBe(true);
    expect(labels.some((l) => l.startsWith("Farm licence renewal"))).toBe(true);
    expect(labels.some((l) => l.startsWith("Deadline"))).toBe(false);
  });

  it("meets its calendar and estimates effort from sizes it has", async () => {
    const user = userEvent.setup();
    wrap(<StrategyView plan={PAYROLL} />);
    await user.click(screen.getByRole("tab", { name: /Calendar/ }));
    expect(screen.getByText(/No conflicts with the brief.s calendar/)).toBeTruthy();
    await user.click(screen.getByRole("tab", { name: /Effort/ }));
    expect(screen.getByText(/Total from the table: \d+–\d+ person-days/)).toBeTruthy();
  });
});
