// @vitest-environment jsdom
import * as React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import fixtures from "@/components/modernization/__tests__/fixtures.json";

/**
 * Phase E — the Target Architecture page (research §6.3), rendering what the BACKEND produces
 * (`fixtures.json` → `target_design` and `legacy_interfaces`, regenerated by
 * help/Track-3/tools/regen_view_fixtures.py; never hand-edited).
 *
 *   - the access gate and the shared frame (documents for THIS stage, stack chip, interfaces);
 *   - sign-off: an Architect who did not produce it is offered Approve; the producer is told why not;
 *   - the hand-over names the NEXT agent (Migration Strategy), not Target Architecture;
 *   - the design view: stats, the pattern mix, modules joined to their contracts, traps and ADRs,
 *     contracts with location/proof/brief words, the chosen ADR option, departures, questions;
 *   - the ledger panel says what approval does before it, and shows live states after;
 *   - the interface inventory, filterable.
 */

const PROJECT = "22222222-2222-2222-2222-222222222222";

const state = vi.hoisted(() => ({
  track: "modernization" as string,
  me: { id: "u-arch2", email: "arch2@example.com" },
  version: {} as Record<string, unknown>,
  ledger: [] as { moduleId: string; moduleName: string; legacyPath: string; state: string }[],
  ledgerCalls: 0,
  documentStages: [] as string[],
}));

vi.mock("next/navigation", () => ({
  useParams: () => ({ id: PROJECT }),
  useRouter: () => ({ push: vi.fn(), replace: vi.fn() }),
  useSearchParams: () => new URLSearchParams(),
  usePathname: () => "/",
}));
vi.mock("@/hooks/use-session", () => ({
  useSession: () => ({ user: state.me,
    permissions: ["artifact:view", "run:create", "artifact:approve_design_modernization"] }),
}));
vi.mock("@/hooks/use-agent-chat", () => ({
  useAgentChat: () => ({
    busy: false, messages: [], sessions: [], sessionId: null, attachments: [], documents: [],
    send: vi.fn(), cancel: vi.fn(), newChat: vi.fn(), selectSession: vi.fn(),
    attachFiles: vi.fn(), removeAttachment: vi.fn(),
  }),
}));
vi.mock("@/hooks/use-chat-deep-link", () => ({ useChatDeepLink: () => null }));
vi.mock("@/lib/api/projects", () => ({
  getProject: async () => ({ id: PROJECT, name: "ClaimTrack", track: state.track }),
}));
vi.mock("@/lib/api/modernization", async (orig) => ({
  ...(await (orig() as Promise<Record<string, unknown>>)),
  getVersionPacket: async (_p: string, stage: string, version: number) => ({
    stage, version, ok: true, problems: [], packet: { payload: {} } }),
  getLegacyInterfaces: async () => fixtures.legacy_interfaces,
}));
vi.mock("@/lib/api/modernization-programme", async (orig) => ({
  ...(await (orig() as Promise<Record<string, unknown>>)),
  getLedger: async () => (state.ledgerCalls++, { projectId: PROJECT, states: [], modules: state.ledger }),
}));
vi.mock("@/lib/api/artifact-versions", async (orig) => ({
  ...(await (orig() as Promise<Record<string, unknown>>)),
  listStageVersions: async () => [state.version],
  getStageVersion: async () => state.version,
  getVersionConsumers: async () => ({ stage: "design_modernization", version: 1, status: "published",
    contentHash: "h", consumers: [] }),
  getVersionStaleness: async () => ({ stage: "design_modernization", version: 1, pinned: true, stale: false, inputs: [] }),
  publishStageVersion: vi.fn(),
  rejectStageVersion: vi.fn(),
}));
vi.mock("@/components/modernization/legacy-code-control", () => ({
  useLegacyCode: () => ({ data: undefined }),
  useAnnouncePullOutcome: () => undefined,
  LegacyCodeStatus: () => null,
  PullLegacyCodeDialog: () => null,
}));
vi.mock("@/components/app/document-list", () => ({
  DocumentList: ({ stage }: { stage: string }) => {
    state.documentStages.push(stage);
    return <section aria-label="documents">documents for {stage}</section>;
  },
}));
vi.mock("@/components/app/tech-stack-chip", () => ({ TechStackChip: () => <span>tech stack chip</span> }));
vi.mock("@/components/app/model-selector", () => ({ ModelSelector: () => null }));
vi.mock("@/components/app/agent-chat-drawer", () => ({ AgentChatDrawer: () => null }));
vi.mock("@/components/app/mermaid-renderer", () => ({
  MermaidRenderer: ({ source }: { source: string }) => <pre aria-label="mermaid">{source}</pre>,
}));

import TargetArchitecturePage from "@/app/(app)/projects/[id]/target-architecture/page";
import { chosenOption, ledgerText, TargetDesignView } from "@/components/modernization/target-design-view";
import { VersionView } from "@/components/modernization/version-view";
import { TargetDesign } from "@/lib/schemas/modernization";

const DESIGN = TargetDesign.parse(fixtures.target_design);

function wrap(ui: React.ReactElement) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(<QueryClientProvider client={client}>{ui}</QueryClientProvider>);
}

beforeEach(() => {
  state.track = "modernization";
  state.me = { id: "u-arch2", email: "arch2@example.com" };
  state.version = { id: "v1", stage: "design_modernization", version: 1, status: "draft", contentHash: "h",
    producedBy: "arch@example.com", covers: [], payload: fixtures.target_design };
  state.ledger = [];
  state.ledgerCalls = 0;
  state.documentStages = [];
});
afterEach(cleanup);

describe("the page", () => {
  it("explains instead of opening a chat on a project of another track", async () => {
    state.track = "greenfield";
    wrap(<TargetArchitecturePage />);
    expect(await screen.findByText("Target Architecture is a Code Modernization agent")).toBeTruthy();
    expect(state.documentStages).toEqual([]);
  });

  it("has the shared frame for its own stage, the stack chip and the legacy interfaces", async () => {
    wrap(<TargetArchitecturePage />);
    expect(await screen.findByText("documents for design_modernization")).toBeTruthy();
    expect(screen.getByText("tech stack chip")).toBeTruthy();
    expect(screen.getByRole("button", { name: "Legacy interfaces" })).toBeTruthy();
    expect(screen.getByRole("heading", { name: "How a target design gets made" })).toBeTruthy();
  });

  it("lists the inventory in the interfaces dialog, filterable by kind and text", async () => {
    const user = userEvent.setup();
    wrap(<TargetArchitecturePage />);
    await user.click(await screen.findByRole("button", { name: "Legacy interfaces" }));
    const dialog = await screen.findByRole("dialog");
    expect(await within(dialog).findByText("GET /api/v1/claims/{id}")).toBeTruthy();
    expect(within(dialog).getByText(/21 found/)).toBeTruthy();
    await user.click(within(dialog).getByRole("button", { name: /^Files \(4\)/ }));
    expect(within(dialog).queryByText("GET /api/v1/claims/{id}")).toBeNull();
    expect(within(dialog).getByText("/out/bank/settlement.txt")).toBeTruthy();
    await user.type(within(dialog).getByRole("textbox", { name: "Filter interfaces" }), "policyhub");
    expect(within(dialog).getAllByRole("row")).toHaveLength(2); // header + the one match
  });
});

function versionView() {
  return wrap(
    <VersionView projectId={PROJECT as never} stage="design_modernization" noun="target design" version={1}
      render={(payload, detail) => (
        <TargetDesignView design={TargetDesign.parse(payload)} projectId={PROJECT as never}
          approved={detail.status === "published"} />
      )} />,
  );
}

describe("sign-off and hand-over", () => {
  it("offers Approve to an Architect who did not produce it, and names Migration Strategy as next", async () => {
    versionView();
    expect(await screen.findByRole("button", { name: "Approve" })).toBeTruthy();
    expect(await screen.findByText("Ready to hand to Migration Strategy once approved.")).toBeTruthy();
    expect(screen.queryByText(/Target Architecture once approved/)).toBeNull();
  });

  it("tells the producer why they cannot decide it", async () => {
    state.me = { id: "u-arch", email: "arch@example.com" };
    versionView();
    expect(await screen.findByText(/You produced this target design, so you can.t approve it/)).toBeTruthy();
    expect(screen.queryByRole("button", { name: "Approve" })).toBeNull();
  });

  it("says what approval does to the ledger, before it happens", async () => {
    versionView();
    const panel = await screen.findByRole("region", { name: "Module ledger" });
    expect(panel.textContent).toContain("Approving this version puts these 5 modules on the migration ledger");
    expect(within(panel).getAllByText("not on the ledger yet")).toHaveLength(5);
  });

  it("shows where each module is once the design is approved", async () => {
    state.version = { ...state.version, status: "published" };
    state.ledger = [{ moduleId: "M-01", moduleName: "claimtrack-core", legacyPath: "claimtrack-core", state: "designed" },
      { moduleId: "M-03", moduleName: "claimtrack-batch", legacyPath: "claimtrack-batch", state: "sequenced" }];
    versionView();
    const panel = await screen.findByRole("region", { name: "Module ledger" });
    await waitFor(() => expect(within(panel).getByText("Sequenced")).toBeTruthy());
    expect(panel.textContent).toContain("This design is approved");
    expect(within(panel).getByText("Designed")).toBeTruthy();
    expect(within(panel).getAllByText("not on the ledger yet")).toHaveLength(3);
  });
});

describe("the ledger after an approval in place", () => {
  it("reads the ledger again when the version it shows becomes the approved one", async () => {
    const client = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: Infinity } } });
    const ui = (approved: boolean) => (
      <QueryClientProvider client={client}>
        <TargetDesignView design={DESIGN} projectId={PROJECT as never} approved={approved} />
      </QueryClientProvider>
    );
    const { rerender } = render(ui(false));
    await waitFor(() => expect(state.ledgerCalls).toBe(1));
    state.ledger = [{ moduleId: "M-01", moduleName: "claimtrack-core", legacyPath: "claimtrack-core", state: "designed" }];
    rerender(ui(true));
    const panel = screen.getByRole("region", { name: "Module ledger" });
    await waitFor(() => expect(within(panel).getByText("Designed")).toBeTruthy());
    expect(state.ledgerCalls).toBe(2);
  });
});

function design() {
  return wrap(<TargetDesignView design={DESIGN} />);
}

describe("the design view", () => {
  it("states what it was built from and the headline numbers", () => {
    design();
    const summary = screen.getByRole("region", { name: "Target design summary" });
    expect(summary.textContent).toContain("Brief v1 (approved)");
    expect(summary.textContent).toContain("Assessment v1 (approved)");
    expect(summary.textContent).toContain("a1b2c3d");
    expect(summary.textContent).toContain("21 legacy interfaces found in the code");
    const mix = screen.getByRole("list", { name: "Migration patterns" });
    expect(mix.textContent).toBe("In-place upgrade × 4Strangler fig × 2Parallel run × 2Rewrite × 1");
  });

  it("says plainly when no legacy code was checked", () => {
    wrap(<TargetDesignView design={{ ...DESIGN, interfaces: null }} />);
    expect(screen.getByText(/No legacy code was pulled — contract locations were not checked/)).toBeTruthy();
  });

  it("shows the target per part of the system", () => {
    design();
    const table = screen.getByRole("region", { name: "Target per part of the system" });
    expect(table.textContent).toContain("Java 21 · Node 24 · Python 3.12");
    expect(screen.getByRole("region", { name: "Data migration" }).textContent).toContain("online replication");
    expect(screen.getByRole("region", { name: "Constraints on the order of the move" }).textContent)
      .toContain("M-01 dual-built");
  });

  it("joins a module to its contracts, traps and decisions", async () => {
    const user = userEvent.setup();
    design();
    await user.click(screen.getByRole("tab", { name: /Modules/ }));
    await user.click(screen.getByRole("cell", { name: "M-03" }));
    const detail = screen.getByRole("complementary", { name: "M-03 detail" });
    expect(detail.textContent).toContain("CT-02 bank payment file");
    expect(detail.textContent).toContain("TR-02 HashMap order feeds settlement lines");
    expect(detail.textContent).toContain("ADR-04 Parallel-run the settlement batch");
    expect(detail.textContent).toContain("Parallel run: Old and new process the same inputs");
    await user.click(screen.getByRole("button", { name: "Rewrite" }));
    expect(screen.getAllByRole("row")).toHaveLength(2);
  });

  it("shows each contract's location, proof, status and the brief's words", async () => {
    const user = userEvent.setup();
    const proposed = { ...DESIGN, frozen_contracts: DESIGN.frozen_contracts.map((c) =>
      c.id === "CT-04" ? { ...c, status: "proposed" as const } : c) };
    wrap(<TargetDesignView design={proposed} />);
    await user.click(screen.getByRole("tab", { name: /Contracts/ }));
    expect(screen.getByText("“bank payment file format”")).toBeTruthy();
    expect(screen.getByText("claimtrack-reports/cr4_return.py")).toBeTruthy();
    expect(screen.getAllByText("Confirmed")).toHaveLength(3);
    expect(screen.getByText("Proposed — needs confirming")).toBeTruthy();
  });

  it("marks the chosen option of each decision, and the departures from the brief", async () => {
    const user = userEvent.setup();
    design();
    await user.click(screen.getByRole("tab", { name: /Decisions/ }));
    const adr1 = screen.getByRole("list", { name: "ADR-01 options" });
    expect(within(adr1).getByLabelText("chosen").parentElement?.textContent).toBe("Rewrite in React 18 + TypeScript");
    expect(screen.getByRole("region", { name: "Departures from the brief" }).textContent).toContain("Container Apps Jobs");
    expect(screen.getByText("departs from the brief")).toBeTruthy();
  });

  it("lists the questions the code could not answer, with their source", async () => {
    const user = userEvent.setup();
    wrap(<TargetDesignView design={{ ...DESIGN, open_questions: ["Who owns the PolicyHub extract?"] }} />);
    await user.click(screen.getByRole("tab", { name: /Questions/ }));
    expect(screen.getByRole("region", { name: "Open questions" }).textContent).toContain("Who owns the PolicyHub extract?");
    expect(screen.getByRole("region", { name: "Answered questions" }).textContent).toContain("from the document");
  });

  it("draws the three diagrams from their Mermaid source", async () => {
    const user = userEvent.setup();
    design();
    await user.click(screen.getByRole("tab", { name: /Diagrams/ }));
    expect(screen.getByLabelText("mermaid").textContent).toContain("flowchart LR");
    await user.click(screen.getByRole("button", { name: "TO-BE container" }));
    expect(screen.getByLabelText("mermaid").textContent).toContain("Azure MySQL 8.4");
  });

  it("shows the checks' notes, never hiding them", () => {
    wrap(<TargetDesignView design={{ ...DESIGN, notes: ["Built from brief v1 (not yet approved): provisional."] }} />);
    expect(screen.getByRole("status", { name: "Notes" }).textContent).toContain("provisional");
  });
});

describe("ledgerText (review fix #9)", () => {
  it("says only what is true for the version's state", () => {
    expect(ledgerText(false, "draft", 5)).toContain("Approving this version puts these 5 modules");
    expect(ledgerText(false, "rejected", 5)).toBe(
      "This version was rejected, so it cannot be approved and does not change the ledger.");
    expect(ledgerText(false, "superseded", 5)).toContain("A newer design has been approved since");
    expect(ledgerText(true, "published", 5)).toContain("This design is approved");
    for (const s of ["rejected", "superseded"]) expect(ledgerText(false, s, 5)).not.toContain("Approving");
  });
});

describe("chosenOption", () => {
  const adr = { id: "ADR-09", title: "t", context: "c", consequences: "x", modules: [], contracts: [],
    options: ["Keep MySQL", "Move to PostgreSQL"], decision: "" };
  it("matches the decision's words, or the option it opens with", () => {
    expect(chosenOption({ ...adr, decision: "move to postgresql" })).toBe("Move to PostgreSQL");
    expect(chosenOption({ ...adr, decision: "Keep MySQL, upgraded to 8.0" })).toBe("Keep MySQL");
    expect(chosenOption({ ...adr, decision: "Something else" })).toBeNull();
  });
});
